package xiroc.doomcall;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import doom.lib.Config;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.Entity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.oredict.ShapedOreRecipe;
import xiroc.doomcall.block.BlockHVGenerator;
import xiroc.doomcall.block.BlockHandler;
import xiroc.doomcall.block.BlockHeavyCoalGenerator;
import xiroc.doomcall.block.BlockItemCrate;
import xiroc.doomcall.entity.EntityDestroyer;
import xiroc.doomcall.item.ItemDestroyer;
import xiroc.doomcall.item.ModItems;
import xiroc.doomcall.item.block.ItemBlockHeavyCoalGenerator;
import xiroc.doomcall.lib.Reference;
import xiroc.doomcall.proxy.CommonProxy;
import xiroc.doomcall.recipe.EMFRecipe;
import xiroc.doomcall.recipe.EMFRecipes;
import xiroc.doomcall.recipe.RecipeHandler;
import xiroc.doomcall.tileentity.TileEntityHVGenerator;
import xiroc.doomcall.tileentity.TileEntityHandler;
import xiroc.doomcall.tileentity.TileEntityItemCrate;
import xiroc.doomcall.util.CreativeTabDoomCall;
import xiroc.doomcall.util.EntityUtil;
import xiroc.doomcall.util.EnumVersionType;
import xiroc.doomcall.util.GuiHandler;
import xiroc.doomcall.util.ModHandler;
import xiroc.doomcall.util.ModVersion;

@Mod(modid = Reference.modid, version = Reference.version, acceptedMinecraftVersions = Reference.acceptedMinecraftVersions, name = Reference.name )
public class DoomCall {

	/**
	 * DoomCall by XIROC * 2016 / 17 DoomCall uses the RF-API (cofh.api)
	 */

	@Instance(Reference.name)
	public static DoomCall instance;
	@SidedProxy(clientSide = Reference.client_proxy, serverSide = Reference.common_proxy)
	public static CommonProxy proxy;

	public static EnumVersionType versionType = EnumVersionType.UNCHECKED;

	public static CreativeTabs creativeTab = new CreativeTabDoomCall();

	public static EMFRecipes recipes0;
	
	public static Config config;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e) {
		config = new Config(e.getModConfigurationDirectory().getPath());
		ModVersion.checkForUpdates();
		ModMetadata m = e.getModMetadata();
		m.name = EnumChatFormatting.RED +""+ EnumChatFormatting.BOLD+"DoomCall";
		m.autogenerated = false;
		ArrayList<String> authors = new ArrayList<String>();
		authors.add(EnumChatFormatting.RED +""+ EnumChatFormatting.ITALIC+"XIROC");
		m.authorList = authors;
		m.description = EnumChatFormatting.GRAY + "";
	}

	@Mod.EventHandler
	public void init(FMLInitializationEvent e) {
		proxy.registerRenderers();
		recipes0 = new EMFRecipes();
		ModItems.registerItems();
		BlockHandler.registerBlocks();
		TileEntityHandler.registerTileEntities();
		EntityUtil.registerEntities();
		NetworkRegistry.INSTANCE.registerGuiHandler(Reference.instance, new GuiHandler());
	}

	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent e) {
		ModHandler.load();
		RecipeHandler.load();
	}

}
